export const seedPayload = {
  categories: [
    { name: 'Programming', slug: 'programming', description: 'Learn to write programs step by step.' },
    { name: 'Database', slug: 'database', description: 'Store, find, and understand data with SQL.' },
    { name: 'Web Development', slug: 'web-development', description: 'Build websites and web apps.' },
    { name: 'Microsoft Tools', slug: 'microsoft-tools', description: 'Excel, Power BI, and Office skills.' },
  ],
  instructors: [
    {
      name: 'Codex Nova Mentor',
      slug: 'codex-nova-mentor',
      designation: 'Mentor',
      expertise: ['Python', 'SQL', 'Web Development'],
      experience: 'Mentors help students learn by doing.',
      bio: 'You will learn with guided practice and clear feedback.',
      social: {},
      published: true,
    },
  ],
  courses: [
    [
      'Python Programming',
      'python',
      'Learn Python from fundamentals to practical programming, including problem-solving, OOP, file handling, and databases.',
      'programming',
    ],
    [
      'SQL & Database Fundamentals',
      'sql',
      'Master database concepts and SQL — from creating tables to joins, views, and practical reporting projects.',
      'database',
    ],
    [
      'C Programming Essentials',
      'c',
      'Learn C from fundamentals through arrays, pointers, structures, and file handling with a hands-on project.',
      'programming',
    ],
    [
      'C++ Programming Mastery',
      'cpp',
      'Learn C++ from basics to OOP, STL, file handling, and exceptions — then build a real application project.',
      'programming',
    ],
    [
      'Java Programming',
      'java',
      'Learn Java from fundamentals through OOP, collections, multithreading, and JDBC with a full application project.',
      'programming',
    ],
    [
      'HTML Web Development',
      'html',
      'Learn HTML structure, forms, semantic markup, and accessibility — then build a personal portfolio website.',
      'web-development',
    ],
    [
      'CSS & Web Styling',
      'css',
      'Style modern websites with CSS — box model, Flexbox, Grid, responsive design, and animations.',
      'web-development',
    ],
    [
      'JavaScript Development',
      'javascript',
      'Learn JavaScript from basics to DOM, ES6+, async programming, and real interactive web projects.',
      'web-development',
    ],
    [
      'Tailwind CSS & Modern UI',
      'tailwind-css',
      'Build modern UIs faster with Tailwind — utilities, responsive layouts, components, and dark mode.',
      'web-development',
    ],
    [
      'React JS Frontend Development',
      'react-js',
      'Build modern React apps with components, hooks, routing, APIs, and a full dashboard project.',
      'web-development',
    ],
    [
      'Power BI & Data Visualization',
      'power-bi',
      'Turn raw data into interactive dashboards with Power Query, data modeling, DAX, and visuals.',
      'microsoft-tools',
    ],
    [
      'Microsoft Excel – Basic to Advanced',
      'excel-basic-to-advanced',
      'Go from Excel basics to advanced lookups, Pivot Tables, charts, and KPI dashboards.',
      'microsoft-tools',
    ],
    [
      'Office Automation & Productivity',
      'office-automation',
      'Build digital office skills across Word, Excel, PowerPoint, email, and productivity workflows.',
      'microsoft-tools',
    ],
    [
      'MS Word – Professional Documentation',
      'ms-word',
      'Create polished resumes, reports, letters, and professional documents in Microsoft Word.',
      'microsoft-tools',
    ],
    [
      'MS Excel – Data & Office Skills',
      'ms-excel',
      'Dedicated Excel path from beginner through advanced analysis, Pivot Tables, and dashboards.',
      'microsoft-tools',
    ],
    [
      'MS PowerPoint – Presentation Design',
      'ms-powerpoint',
      'Design and deliver professional presentations with layouts, visuals, animations, and Slide Master.',
      'microsoft-tools',
    ],
  ].map(([title, slug, shortDescription, categorySlug]) => ({
    title,
    slug,
    shortDescription,
    description: shortDescription,
    categorySlug,
    instructorSlug: 'codex-nova-mentor',
    level: 'Beginner',
    duration: '8 Weeks',
    durationWeeks: 8,
    mode: 'Online',
    projectCount: 3,
    fee: 'Fee on enquiry',
    feeAmount: 0,
    skills: [title],
    tools: [title],
    projects: ['Guided practice project'],
    prerequisites: ['A computer and a willingness to practise.'],
    certificate: 'Certificate details will be shared when you enroll.',
    curriculum: [{ title: 'Getting started', topics: ['Basics', 'Practice', 'Project'] }],
    faqs: [],
    relatedSlugs: [],
    featured: true,
    status: 'published',
  })).map((course) => {
    const schedule: Record<string, { duration: string; durationWeeks: number; totalHours: number; classCount: number }> = {
      python: { duration: '8 Weeks', durationWeeks: 8, totalHours: 60, classCount: 40 },
      sql: { duration: '6 Weeks', durationWeeks: 6, totalHours: 45, classCount: 30 },
      c: { duration: '6 Weeks', durationWeeks: 6, totalHours: 45, classCount: 30 },
      cpp: { duration: '6.8 Weeks', durationWeeks: 6.8, totalHours: 50, classCount: 34 },
      java: { duration: '8 Weeks', durationWeeks: 8, totalHours: 60, classCount: 40 },
      html: { duration: '3.6 Weeks', durationWeeks: 3.6, totalHours: 26, classCount: 18 },
      css: { duration: '4 Weeks', durationWeeks: 4, totalHours: 30, classCount: 20 },
      javascript: { duration: '8 Weeks', durationWeeks: 8, totalHours: 60, classCount: 40 },
      'tailwind-css': { duration: '4 Weeks', durationWeeks: 4, totalHours: 30, classCount: 20 },
      'react-js': { duration: '8 Weeks', durationWeeks: 8, totalHours: 60, classCount: 40 },
      'power-bi': { duration: '5.4 Weeks', durationWeeks: 5.4, totalHours: 40, classCount: 27 },
      'excel-basic-to-advanced': { duration: '6 Weeks', durationWeeks: 6, totalHours: 45, classCount: 30 },
      'office-automation': { duration: '4 Weeks', durationWeeks: 4, totalHours: 30, classCount: 20 },
      'ms-word': { duration: '2.8 Weeks', durationWeeks: 2.8, totalHours: 20, classCount: 14 },
      'ms-excel': { duration: '6 Weeks', durationWeeks: 6, totalHours: 45, classCount: 30 },
      'ms-powerpoint': { duration: '2.8 Weeks', durationWeeks: 2.8, totalHours: 20, classCount: 14 },
    };
    return { ...course, ...(schedule[course.slug] ?? { totalHours: 0, classCount: 0 }) };
  }),
  projects: [
    {
      title: 'Simple Dashboard Practice',
      slug: 'simple-dashboard-practice',
      category: 'Data',
      technologies: ['Python', 'Excel', 'Power BI'],
      shortDescription: 'Clean a small dataset and show it in a clear dashboard.',
      description: 'A beginner-friendly practice project using simple data.',
      outcomes: ['A short report', 'A simple dashboard'],
      published: true,
    },
  ],
  events: [
    {
      title: 'C Language Batch Starting Soon',
      slug: 'c-language-batch-starting-soon',
      type: 'bootcamp',
      date: 'Starting soon',
      time: 'To be announced',
      location: 'Online',
      mode: 'Online',
      description: 'Upcoming C Language batch. Learn C from the basics with practice.',
      speaker: 'Codex Nova Mentor',
      registrationOpen: true,
      published: true,
    },
    {
      title: 'C++ Language Batch Starting Soon',
      slug: 'cpp-language-batch-starting-soon',
      type: 'bootcamp',
      date: 'Starting soon',
      time: 'To be announced',
      location: 'Online',
      mode: 'Online',
      description: 'Upcoming C++ Language batch. Build logic with guided support.',
      speaker: 'Codex Nova Mentor',
      registrationOpen: true,
      published: true,
    },
    {
      title: 'Java Language Batch Starting Soon',
      slug: 'java-language-batch-starting-soon',
      type: 'bootcamp',
      date: 'Starting soon',
      time: 'To be announced',
      location: 'Online',
      mode: 'Online',
      description: 'Upcoming Java Language batch. Learn Java step by step.',
      speaker: 'Codex Nova Mentor',
      registrationOpen: true,
      published: true,
    },
    {
      title: 'Python Language Batch Starting Soon',
      slug: 'python-language-batch-starting-soon',
      type: 'bootcamp',
      date: 'Starting soon',
      time: 'To be announced',
      location: 'Online',
      mode: 'Online',
      description: 'Upcoming Python Language batch. Start Python from the basics.',
      speaker: 'Codex Nova Mentor',
      registrationOpen: true,
      published: true,
    },
  ],
  posts: [
    {
      title: 'How students can actually learn Python',
      slug: 'how-engineering-students-should-learn-python',
      excerpt: 'Skip the endless tutorial loop. Learn Python by writing small tools.',
      content:
        '## Start smaller than you think\n\nPick one repetitive task and automate it.\n\n## Projects beat playlists\n\nPublish a README and show what broke.',
      category: 'Python',
      author: 'Codex Nova Faculty',
      publishedAt: '2026-06-12',
      readingTime: '7 min',
      seoTitle: 'How students can learn Python | Codex Nova',
      metaDescription: 'Practical Python learning advice for beginners.',
      headings: [
        { id: 'start-smaller-than-you-think', text: 'Start smaller than you think' },
        { id: 'projects-beat-playlists', text: 'Projects beat playlists' },
      ],
      published: true,
    },
    {
      title: 'SQL is a useful career skill',
      slug: 'sql-is-a-career-skill',
      excerpt: 'If you can join tables and define a metric, you become useful fast.',
      content:
        '## Why SQL shows up everywhere\n\nInternships assume you can ask a database a precise question.\n\n## How to practise without a job\n\nUse sample schemas and write the question in English first.',
      category: 'SQL',
      author: 'Codex Nova Faculty',
      publishedAt: '2026-06-20',
      readingTime: '6 min',
      seoTitle: 'Why students should learn SQL | Codex Nova',
      metaDescription: 'Why SQL helps students in internships and projects.',
      headings: [
        { id: 'why-sql-shows-up-everywhere', text: 'Why SQL shows up everywhere' },
        { id: 'how-to-practise-without-a-job', text: 'How to practise without a job' },
      ],
      published: true,
    },
  ],
  testimonials: [],
  faqs: [
    {
      question: 'Who can join Codex Nova?',
      answer:
        'Students from different educational backgrounds. You do not need to be an engineering student.',
      audience: 'general',
      published: true,
    },
    {
      question: 'Do you guarantee jobs or salary packages?',
      answer: 'No. We help you learn skills and prepare. Job results depend on your effort and the market.',
      audience: 'general',
      published: true,
    },
    {
      question: 'Are classes online?',
      answer: 'Yes. Classes are currently online. Other modes may be added later.',
      audience: 'general',
      published: true,
    },
  ],
};
